import type { AnalysisModel } from '@/types/case-workspace';

export function exportJson(raw: unknown, caseId: string) {
  const jsonString = `data:text/json;charset=utf-8,${encodeURIComponent(JSON.stringify(raw ?? {}, null, 2))}`;
  const a = document.createElement('a');
  a.setAttribute('href', jsonString);
  a.setAttribute('download', `LexOrch_Analysis_${caseId}.json`);
  document.body.appendChild(a);
  a.click();
  a.remove();
}

function docHtml(a: AnalysisModel): string {
  const esc = (s: string) => s.replace(/&/g, '&amp;').replace(/</g, '&lt;').replace(/>/g, '&gt;');
  const statutes = a.statutes.map((s) => `<li>${esc(s.display)}</li>`).join('');
  const precedents = a.precedents.map((p) => `<li><b>${esc(p.name)}</b> ${esc(p.citation)}${p.summary ? `<br/><span style="color:#555">${esc(p.summary)}</span>` : ''}</li>`).join('');
  const issues = a.issues.map((i, n) => `<li><b>Issue ${n + 1}.</b> ${esc(i.text)}</li>`).join('');
  return `
  <html xmlns:o="urn:schemas-microsoft-com:office:office" xmlns:w="urn:schemas-microsoft-com:office:word">
  <head><meta charset="utf-8"><title>LexOrch Advisory Brief</title></head>
  <body style="font-family:Georgia,serif; line-height:1.6">
    <h1 style="border-bottom:2px double #333">${esc(a.caseTitle.value)}</h1>
    <p style="font-size:10pt;color:#555">${esc(a.courtChip.value)} · ${esc(a.dateChip.value)} · Trust Index ${a.trustScore}%</p>
    <h2>Executive Summary</h2><p>${esc(a.summary.value)}</p>
    ${issues ? '<h2>Legal Issues</h2><ol>' + issues + '</ol>' : ''}
    ${statutes ? '<h2>Statutes &amp; Articles</h2><ul>' + statutes + '</ul>' : ''}
    ${precedents ? '<h2>Judicial Precedents</h2><ul>' + precedents + '</ul>' : ''}
    <h2>Operative Conclusion</h2><p>${esc(a.conclusion.value)}</p>
    <p style="font-size:9pt;color:#777;border-top:1px solid #ccc;padding-top:8px">Generated by LexOrch-KG · Verified under dual-agent debate · BGE-M3 / Qdrant / FalkorDB grounding</p>
  </body></html>`;
}

export function exportDocx(analysis: AnalysisModel, caseId: string) {
  const blob = new Blob(['\ufeff', docHtml(analysis)], { type: 'application/msword' });
  const url = URL.createObjectURL(blob);
  const a = document.createElement('a');
  a.href = url;
  a.download = `LexOrch_Brief_${caseId}.doc`;
  document.body.appendChild(a);
  a.click();
  a.remove();
  URL.revokeObjectURL(url);
}
